<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.jgallegol.api</groupId>
    <artifactId>RetoAutomatizacionApiKarate</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>

        <!-- Version de Java utilizada por el proyecto -->
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>

        <!-- Version actual de Karate -->
        <karate.version>1.5.2</karate.version>

    </properties>

    <dependencies>

        <!-- Dependencia principal de Karate -->
        <dependency>
            <groupId>io.karatelabs</groupId>
            <artifactId>karate-junit5</artifactId>
            <version>${karate.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <testResources>
            <testResource>
                <directory>src/test/java</directory>
                <includes>
                    <include>**/*.feature</include>
                    <include>**/*.json</include>
                    <include>**/*.js</include>
                </includes>
            </testResource>
        </testResources>

        <plugins>

            <!-- Permite ejecutar pruebas Karate desde Maven -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
            </plugin>

        </plugins>

    </build>

</project>